modLoader="javafml" #mandatory
loaderVersion="[39,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
[[mods]] #mandatory
modId="thump" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Thump!" #mandatory
credits="Vaky (art, idea, lead) and Coda (code)" #optional
description='''A small, quality of life mod to improve rabbit behavior!'''
